# Fehlerbehandlung ‚ùå<!-- omit in toc -->

- [Throwable](#throwable)
- [Errors](#errors)
- [Exceptions](#exceptions)
- [try-catch-finally](#try-catch-finally)
- [throws](#throws)
- [try-with-resources](#try-with-resources)
- [Weiterf√ºhrende Links](#weiterf√ºhrende-links)


## Throwable
In Programmen k√∂nnen verschiedene Fehler auftreten. All diese Fehler sind (auf h√∂chster Ebene) durch das Interface `Throwable` repr√§sentiert (siehe Grafik unten!). Der Name kommt daher, dass man auch sagt, ein auftretender Fehler wird "_geworfen_" (eng. _thrown_). D.h. das Programm teilt mit, dass an einer bestimmten stelle des Codes ein Fehler aufgetreten ist. Man unterscheidet zwischen zwei Arten von Fehlern: **Errors** und **Exceptions** (siehe auch hier Grafik unten!).

![Exceptions/Errors Class Hierarchy](../assets/images/Exception-Hierarchy-Diagram.jpeg)  
> _Quelle: [programcreek.com](http://www.programcreek.com/2009/02/diagram-for-hierarchy-of-exception-classes/)_


## Errors

**Errors** sind Fehler, die _nicht aufgefangen werden k√∂nnen_ (_catch_), d.h. das Programm kann nicht konstruktiv auf sie reagieren. Sie bringen das Programm unweigerlich zum Absturz. Sie entstehen etwa durch fehlende Systemressourcen. Beispiele hierf√ºr sind `OutOfMemoryError` (mehr üîó [hier](https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/memleaks002.html)) oder `StackOverflowError` (mehr üîó [hier](https://dzone.com/articles/stackoverflowerror-causes-amp-solutions)).

```java
// dieser Code f√ºhrt zu einem OutOfMemoryError
String s = "ThisWillThrowAnError";
while(true) {
	s += s;
}
```

```java
// das Aufrufen dieser Methode f√ºhrt zu einem StackOverflowError
public static void stackOverflow() {
	stackOverflow();
}
```


## Exceptions

Exceptions sind Fehler, die durch eine korrekte Fehlerbehandlung "_aufgefangen_" werden k√∂nnen (eng. _catch_). In diesem Fall wei√ü das Programm mit einem Fehler umzugehen und kann weiter ausgef√ºhrt werden. 

Es werden "_checked_" und "_unchecked_" Exceptions unterschieden: _Checked_ Exceptions sind solche Exceptions, deren m√∂gliches Auftreten au√üerhalb der Kontrolle des Programmes liegen. Beispiele sind die `IllegalArgumentException` oder alle Spezialisierungen von `IOException` (siehe Grafik oben!). _Unchecked_ Exceptions hingegen ergeben sich zur Laufzeit des Programmes durch fehlerhaften oder unsauberen Code und sollten im Idealfall gar nicht erst auftreten (siehe `NullPointerException`, `IllegalArgumentException`, `ArrayIndexOutOfBoundsException`, usw. in der Grafik oben!). Sie k√∂nnen nicht vorhergesagt werden und lassen sich nur durch das schreiben von gutem, fehlerfreiem Code verhindern! Deshalb ist es (bis auf einige Ausnahmen) auch nicht ratsam, f√ºr _Unchecked Exceptions_ eine Fehlerbehandlung durchzuf√ºhren.

```java
// dieser Code erzeugt eine NullPointerException,
// weil auf ein Array-Element zugegriffen wird, das null ist.
String[] s = new String[2];
System.out.println(s[0].length());
```

```java
// dieser Code erzeugt eine ArrayIndexOutOfBoundsException,
// weil auf einen Array-Index zugegriffen wird, der nicht existiert.
String[] s = new String[2];
System.out.println(s[7]);
```

```java
// dieser Code erzeugt eine ArithmeticException: / by zero,
// weil durch die Z√§hlvariable i (mit dem Wert 0) geteilt wird.
for (int i = 5; i >= -5; i--) {
	System.out.println(5 / i);
}
```

Exceptions k√∂nnen durch den Code bewusst "_geworfen_" (eng. _throw_), also ausgel√∂st, oder - um mit ihnen umzugehen - "_aufgefangen_" werden (eng. _catch_). Genau damit besch√§ftigen sich die folgenden Kapitel.

> üîó Vertiefender Artikel: [Checked and Unchecked Exceptions](https://www.baeldung.com/java-checked-unchecked-exceptions)

> üîó Vertiefender Artikel: [Common Java Exceptions](https://www.baeldung.com/java-common-exceptions)

## try-catch-finally

Mit einem Statement aus `try`, `catch` und `finally` wird der Umgang mit potentiellen Exceptions definiert. Ein solches Statement (siehe Beispiel unten!) wird immer dann verwendet, wenn es aufgrund einer checked Exception vom Compiler verlangt wird, oder wenn der/die Programmierer*in
damit rechnet, dass ein Code unter bestimmten Bedingungen eine Exception werfen k√∂nnte.

> üë®‚Äçüè´ Es sollten generell **keine Runtime Exceptions** mit `try`/`catch` behandelt werden, denn diese sollten eigentlich gar nicht auftreten! Programmierfehler, die so schwerwiegend sind, dass sie das Auftreten von Runtime Exceptions zulassen, _sollten sogar zum Absturz des Programmes f√ºhren_. Diese Fehler m√ºssen **korrigiert und vermieden** werden anstatt sie zu **behandeln**.

Der `try`-Block enth√§lt den Code, der eine Exception verursachen k√∂nnte. Mindestens ein `catch`-Block enth√§lt den Code, der im Falle einer bestimmten Exception ausgef√ºhrt werden soll. Ein `catch`-Block wird nur dann ausgef√ºhrt, wenn die geworfene Exception innerhalb des `try`-Blocks geworfen wird und die Art der Exception der im Kopf des `catch`-Blocks angegebenen Exception entspricht (siehe Beipspiel unten!). Der `finally`-Block (falls vorhanden, er ist optional!) enth√§lt Code, der unabh√§ngig von einem ausgel√∂sten `catch`-Block **am Ende der Fehlerbehandlung** auf jeden Fall ausgef√ºhrt werden soll. Dabei spielt es keine Rolle, ob ein Fehler aufgetreten ist!

![try-catch-finally-flow](../assets/images/java-try-catch-finally-flow.jpg)  
> _Quelle: [howtodoinjava.com](https://howtodoinjava.com/java/exception-handling/try-catch-finally/)_

Nach dem _try-catch(-finally)_-Statement wird der darauf folgende Programm-Code weiter ausgef√ºhrt. Falls im `try`-Block kein Fehler auftritt, werden alle `catch`-Bl√∂cke ignoriert; ein etwaiges `finally` wird aber generell ausgef√ºhrt. Falls keiner der definierten `catch`-Bl√∂cke die geworfene Exception abf√§ngt, wird trotzdem ein evtl. vorhandener `finally`-Block ausgef√ºhrt, bevor die Exception dann von der default-Fehlerbehandlung verarbeitet wird (üîó [StackTrace](https://en.wikipedia.org/wiki/Stack_trace) √ºber den üîó [Stderr](https://en.wikipedia.org/wiki/Standard_streams#Standard_error_(stderr)) auf der Konsole ausgeben).


**Syntax und Beispiel:**

Nehmen wir den folgenden kurzen Code an, der eine neue, leere Datei erstellen soll. Die aufgerufene Methode `createNewFile()` wirft ggf. eine `IOException` (_checked_!) oder auch eine `SecurityException` (_unchecked_!):

```java
File f = new File("datei.txt");
f.createNewFile();
```

Um nun mit diesen m√∂glichen Exceptions umzugehen, damit sie unser Programm nicht vorzeitig beenden, nehmen wir f√ºr diesen Aufruf in einem `try`/`catch`-Block eine entsprechende Fehlerbehandlung vor:

```java
File f = new File("datei.txt");

try {
    f.createNewFile();
} catch (IOException e) {
    System.err.println("Datei konnte nicht erstellt werden!");
} catch (Exception e2) {
    System.err.println("Unbekannter Fehler aufgetreten!");
}
        
System.out.println("...das Leben geht weiter!");
```

Das Programm l√§uft also _nach_ einer etwaigen Exception weiter! Nat√ºrlich sollte man sich in der Fehlerbehandlung genau √ºberlegen, wie man auf den entsprechenden Fehler wirklich reagieren m√∂chte. Statt nur eine Meldung auf der Konsole auszugeben, k√∂nnte hier z.B. ggf. vom User ein anderer Dateipfad erfragt werden (o.√§.).


## throws

Eine Methode kann explizit dazu in der Lage sein, eine bestimmte Exception zu "_werfen_". Dies wird mit dem Schl√ºsselwort `throws` markiert. Der Typ der Exception muss dabei angegeben werden. Methoden, in denen diese "_werfende_" Methode aufgerufen wird, _m√ºssen_ eine Fehlerbehandlung vornehmen (Ausnahme: Exceptions vom Typ `RuntimeException`)!

```java
public String thisWillFail() throws IOException {
    return Files.readString(
        new File("this_file_doesnt_exist.haha").toPath());
}
```


## try-with-resources

> ‚ö†Ô∏è Die Lekt√ºre dieses Kapitels empfiehlt sich erst, wenn die Inhalte zu [Input / Output (I/O)](IO.md) bereits bekannt sind!

Eine Spezialform der Fehlerbehandlung f√ºr im `try`-Block verwendete Ressourcen, die nach ihrer Verwendung wieder geschlossen werden m√ºssen (etwa beim Arbeiten mit Datenstr√∂men) ist das sog. _try-with-resources_-Statement.

Der `try`-Block deklariert die entsprechende(n) Ressource(n) (mehrere Ressourcen durch `;` getrennt m√∂glich!) in runden Klammern nach dme `try`. Normalerweise w√ºrde man die verwendeten Ressourcen im `finally`-Block schlie√üen - dies geschieht hier aber automatisch! Diese Form des `try`-Blocks funktioniert mit allen Ressourcen, die `java.lang.AutoCloseable` implementieren (schlie√üt `java.lang.Closeable` ein, denn `Closeable` erweitert `AutoCloseable`).

**Beispiel Datei einlesen OHNE try-with-resources**

```java
BufferedReader br = null;
String line;

try {
	br = new BufferedReader(new FileReader("text.txt"));
	while ((line = br.readLine()) != null) {
		System.out.println("Zeile gelesen: " + line);
	}
} catch (IOException e) {
	System.out.println("IOException im try-Block: " + e.getMessage());
} finally {
	System.out.println("Ausf√ºhrung finally-Block...");
	//so m√ºsste man den Reader eigentlich schlie√üen:
	try {
		if (br != null) {
			br.close();
		}
	} catch (IOException e) {
		System.out.println("IOException im finally-Block: " + e.getMessage());
	}
}
```

**Beispiel Datei einlesen MIT try-with-resources**

```java
String line;

try (BufferedReader br = new BufferedReader(new FileReader("text.txt"))) {
	while ((line = br.readLine()) != null) {
		System.out.println("Zeile gelesen: " + line);
	}
} catch (IOException e) {
	System.out.println("IOException im try-Block: " + e.getMessage());
}
```


## Weiterf√ºhrende Links
- [Difference Between Error and Exception in Java](https://techdifferences.com/difference-between-error-and-exception.html)
- [ORACLE Lesson: Exceptions](https://docs.oracle.com/javase/tutorial/essential/exceptions/)
- [List of Java Exceptions](https://programming.guide/java/list-of-java-exceptions.html)




